; HongJing installer (auto-generated by package_win.ps1)
#define MyAppName "ºè¾µ"
#define MyAppExe  "scrcpy_client_flutter.exe"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Guangzhou Shirui Electronics Co., Ltd."

[Setup]
AppId={{B6E4D4F9-9E86-4E7F-8A1C-C6F9B0F8C3A1}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\HongJing
DefaultGroupName={#MyAppName}
OutputDir=..\build\dist
OutputBaseFilename=HongJing-Setup-1.0.0
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
MinVersion=10.0.17763
SetupIconFile=..\windows\runner\resources\app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExe}
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "chs"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Files]
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{userprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExe}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExe}"

[Run]
Filename: "{app}\{#MyAppExe}"; Description: "Æô¶¯ ºè¾µ"; Flags: nowait postinstall skipifsilent
